package de.ritzelprimpf.toniqo.keyfinder.domain

import de.ritzelprimpf.toniqo.common.model.ScaleType
import de.ritzelprimpf.toniqo.keyfinder.domain.model.ScaleCandidate

/**
 * An immutable catalog of scale candidates for the Key Finder matching engine.
 *
 * @property candidates The list of [ScaleCandidate]s that the matching engine scores against.
 *   In production the list has exactly **168 entries** (12 roots × 14 scale types), covering
 *   every (pitch class, scale type) pair exactly once.
 *   Tests may supply a trimmed list via the constructor to exercise specific scenarios in
 *   isolation without scoring all 168 candidates.
 */
class ScaleCatalog(val candidates: List<ScaleCandidate>) {

    companion object {

        /**
         * The default production catalog: 168 candidates generated by pairing each of the
         * 12 pitch classes (0 = C … 11 = B) with each of the 14 [ScaleType]s.
         *
         * 168 = 12 roots × 14 scale types. Every (root, type) pair appears exactly once.
         * The list is computed once at class-load time and is immutable.
         */
        val DEFAULT: ScaleCatalog = ScaleCatalog(
            buildList {
                for (rootPc in 0 until 12) {
                    for (type in ScaleType.entries) {
                        add(ScaleCandidate(rootPitchClass = rootPc, type = type))
                    }
                }
            },
        )
    }
}
